#            	Fonts
font_family JetBrains Mono 
disable_litigatures never 
font_size 18 



# 		mappings
kitty_mod cmd+shift 


#		windwos specific mappings 
map cmd+enter new_window 
map cmd+1 first_window 
map cmd+2 second_windiow




#		Background 
background_opacity 0.8  




#		macOS specific customisation taylor to my needs 
	
macos_traditional_fullscreen yes
macos_show_window_title_in all
macos_thicken_font 0.0 		


# might include symbol_map 
#
#
#
#


#include current_theme.conf 
